### PR TITLE
Addressed issues with 2019-03 compatibility

### LINKED ISSUE #11: The old Luna formatter does not work with 2019-03
I will try to fix this over the weekend. It looks like they removed a bunch of public fields again.

Adding this issue so those coming here to report the issue know that it is being worked on.

### PR DESCRIPTION
**Pull request by isaki**
- Refactored legacy adapter code in Luna into its own class.
- Implemented legacy adapter use in Luna and Neon formatters.
- Added a ton of suppress warning directive to reduce 600+ warnings to
just 5.
- Updated README.
- Set version to 1.3.0; 1.2.1 doesn't seem appropriate given how much
code was altered and to make it easier to associate versions with
Eclipse compatibility; for example 1.2.1 should share compatibility with
1.2.0. This was a mistake I made when I first added support for 2018-12
(1.1.6 should have been 1.2.0).

**NOTE 1:** I cleaned up a bunch of whitespace by happenstance.
**NOTE 2:** I wrote a Perl script that read a filter of the diff to make sure I replaced all the right values with their new legacy methods as this is a long diff to read line by line. The script passed.

This (tentatively) fixes #11.

### CODE REVIEW

**Comment by isaki** [comment]
You don't have to merge this if you don't want. I'm going to be creating a 1.3.1 to replace my shotgun approach to fixing the current set of issues with something a bit more elegant. You can merge this to get something working out if we need, but I intend to have something today or tomorrow that will actually reflect the new individualized options correctly in Luna. I'll try to do so for Neon as well, but I am admittedly not as familiar with that code yet. I'm hoping it is equally straightforward to do.

**Comment by isaki** [comment]
Alright, 1.3.1 has been pushed to my branch. Please review.

**Comment by isaki** [comment]
Any thoughts?

**Comment by alostale** [comment]
Hi @isaki,

Sorry for the late reaction, I've merged your PR and released a new version.

Thanks

**Pull request merged**
